# Generated by Django 6.0.5 on 2026-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
