# Generated by Django 6.0.5 on 2026-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
