# Generated by Django 6.0.6 on 2026-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_fix_branch_decimal_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='employee',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
