# Generated by Django 6.0.6 on 2026-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_remove_employee_is_validated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='validation_status',
            new_name='face_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
