# Generated by Django 6.0.5 on 2026-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0004_attendance_browser_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
