# Generated by Django 6.0.5 on 2026-06-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0005_employee_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='presensi.branch'),
        ),
    ]
