# Generated by Django 6.0.5 on 2026-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0006_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='face_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
